import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';

const cityNames:Record<string,string>={vancouver:'Vancouver',burnaby:'Burnaby',surrey:'Surrey',coquitlam:'Coquitlam','maple-ridge':'Maple Ridge',chilliwack:'Chilliwack',metrotown:'Metrotown',langley:'Langley',richmond:'Richmond',delta:'Delta',abbotsford:'Abbotsford',mission:'Mission','new-westminster':'New Westminster','north-vancouver':'North Vancouver','west-vancouver':'West Vancouver','pitt-meadows':'Pitt Meadows','port-coquitlam':'Port Coquitlam','port-moody':'Port Moody','white-rock':'White Rock'};
const localDetails:Record<string,{focus:string;areas:string;conditions:string}>={
  vancouver:{focus:'dense commercial sites, strata towers, loading areas and high-traffic sidewalks',areas:'Downtown, Kitsilano, Mount Pleasant, East Vancouver, Kerrisdale and South Vancouver',conditions:'wet coastal snowfall, overnight freezing and limited snow-storage space'},
  burnaby:{focus:'strata communities, retail centres, office sites and steep residential access',areas:'Metrotown, Brentwood, Edmonds, Burnaby Heights, Capitol Hill and South Slope',conditions:'elevation changes, shaded ice and busy pedestrian routes'},
  surrey:{focus:'large commercial lots, industrial yards, strata properties and long private lanes',areas:'Guildford, Newton, Fleetwood, Cloverdale, South Surrey and Whalley',conditions:'large service footprints, variable elevations and repeated freeze-thaw cycles'},
  coquitlam:{focus:'hillside strata, retail properties, schools and managed residential sites',areas:'Burke Mountain, Westwood Plateau, Austin Heights, Maillardville and Coquitlam Centre',conditions:'higher-elevation accumulation, steep grades and early-morning refreeze'},
  'maple-ridge':{focus:'commercial properties, rural access, strata communities and acreage driveways',areas:'Haney, Albion, Silver Valley, Hammond, Cottonwood and Thornhill',conditions:'foothill snowfall, longer access routes and mixed urban-rural service needs'},
  chilliwack:{focus:'commercial centres, industrial yards, agricultural access and managed communities',areas:'Downtown Chilliwack, Sardis, Vedder, Garrison Crossing, Rosedale and Yarrow',conditions:'Fraser Valley snow events, freezing fog and broad service areas'},
  langley:{focus:'warehouses, shopping centres, strata complexes, farms and private roads',areas:'Langley City, Willoughby, Walnut Grove, Brookswood, Murrayville, Aldergrove and Fort Langley',conditions:'wide service areas, industrial traffic and changing conditions from west to east'},
  richmond:{focus:'distribution sites, retail centres, strata communities, hotels and airport-area properties',areas:'Brighouse, Steveston, Broadmoor, East Richmond, Bridgeport and Sea Island',conditions:'wet snow, rapid melt, drainage concerns and overnight black ice'},
  delta:{focus:'industrial sites, port-related properties, retail areas and residential communities',areas:'Ladner, Tsawwassen, North Delta, Tilbury and Annacis Island',conditions:'wind exposure, freezing surfaces and large industrial access routes'},
  abbotsford:{focus:'industrial yards, agricultural operations, retail properties and strata developments',areas:'Clearbrook, West Abbotsford, Downtown, Sumas, Matsqui and Auguston',conditions:'heavier Fraser Valley accumulation, freezing fog and extensive properties'},
  mission:{focus:'hillside homes, commercial sites, strata properties and rural access roads',areas:'Downtown Mission, Hatzic, Cedar Valley, Silverdale and Stave Falls',conditions:'steep grades, higher elevations and longer response routes'},
  'new-westminster':{focus:'strata towers, heritage properties, commercial streets and institutional sites',areas:'Downtown, Uptown, Sapperton, Queensborough, West End and Glenbrooke North',conditions:'steep streets, compact sites and heavy pedestrian traffic'},
  'north-vancouver':{focus:'hillside strata, retail properties, schools and mountain-access communities',areas:'Lonsdale, Lynn Valley, Deep Cove, Edgemont, Capilano and Seymour',conditions:'higher snowfall, steep access and fast-changing mountain weather'},
  'west-vancouver':{focus:'steep residential properties, private roads, strata sites and village commercial areas',areas:'Ambleside, Dundarave, British Properties, Caulfeild, Horseshoe Bay and Cypress Park',conditions:'elevation-driven accumulation, steep driveways and limited equipment access'},
  'pitt-meadows':{focus:'agricultural access, commercial sites, strata communities and industrial properties',areas:'Central Pitt Meadows, Osprey Village, South Bonson and the Lougheed corridor',conditions:'open wind exposure, freezing fog and long flat access routes'},
  'port-coquitlam':{focus:'industrial properties, commercial plazas, strata sites and institutional access',areas:'Downtown PoCo, Citadel, Riverwood, Mary Hill, Lincoln Park and Oxford Heights',conditions:'mixed industrial-residential routes, drainage and overnight refreeze'},
  'port-moody':{focus:'hillside strata, waterfront properties, retail sites and managed communities',areas:'Newport Village, Suter Brook, Heritage Mountain, College Park and Moody Centre',conditions:'steep grades, shaded ice and higher-elevation snowfall'},
  'white-rock':{focus:'hillside residences, waterfront businesses, strata properties and medical access',areas:'Uptown, Five Corners, East Beach, West Beach and Semiahmoo',conditions:'steep coastal streets, wet snowfall and overnight freezing'},
};
const utility:Record<string,{title:string;intro:string}>={
  bc:{title:'British Columbia Snow Removal Information',intro:'Planning resources for winter property maintenance across British Columbia, with a focus on the Lower Mainland and Fraser Valley.'},
  marketing:{title:'Snow Removal Contractor Marketing',intro:'A practical industry resource for operators who want clearer positioning, stronger local visibility and better connections with property managers.'},
  cities:{title:'Lower Mainland Snow Removal Service Areas',intro:'Local winter information and service connections for communities throughout Metro Vancouver and the Fraser Valley.'},
  resources:{title:'Snow Removal Resources',intro:'Equipment guidance, property planning, municipal responsibilities and winter-readiness information for managers and contractors.'},
  contact:{title:'Request Snow Removal Service',intro:'Tell the PlowWow team about the property, current conditions, timing and equipment or labour you may require.'},
  equipment:{title:'Request Snow Removal Equipment or Crews',intro:'Match the property and storm conditions to shovel crews, blowers, sweepers, plow trucks, ATVs, salters, skid steers, backhoes or front loaders.'},
};

export function generateStaticParams(){return [...Object.keys(cityNames),...Object.keys(utility), 'burnby-strata-snow-plow-company'].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const name=cityNames[slug];const page=utility[slug];return {title:name?`${name} Snow Removal Guide`:page?.title||'Snow Removal TV',description:name?`Snow removal information, property planning and service connections for ${name}, BC.`:page?.intro}}

export default async function DetailPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;if(slug==='burnby-strata-snow-plow-company')redirect('/burnaby/');const name=cityNames[slug];const page=utility[slug];if(!name&&!page)notFound();
  const title=name?`${name} snow removal guide`:page.title;const intro=name?`Winter property planning, local responsibilities and storm-ready snow removal service connections for ${name}.`:page.intro;
  const equipment=slug==='equipment';
  return <main><header className="site-header"><Link href="/" className="brand"><span>SNOW</span>REMOVAL.TV</Link><nav><Link href="/cities/">Service Areas</Link><Link href="/equipment/">Equipment</Link><Link href="/resources/">Resources</Link><Link href="/contact/">Contact</Link></nav><a className="header-cta" href="tel:+16047611518">Call 604-761-1518</a></header>
    <section className="detail-hero"><p className="eyebrow">SnowRemoval.tv × PlowWow</p><h1>{title}</h1><p>{intro}</p><div className="actions"><a className="button primary" href="tel:+16047611518">Call for service</a><a className="button ghost" href="sms:+16047611518">Text the team</a></div></section>
    {equipment?<EquipmentContent/>:slug==='cities'?<CitiesContent/>:<GuideContent name={name||'your property'} detail={localDetails[slug]}/>}<section className="cta"><p className="eyebrow">Ready to plan the response?</p><h2>Describe the site, timing and current conditions.</h2><div className="actions"><a className="button light" href="mailto:wow@plowwow.com?subject=Snow%20removal%20request">Email wow@plowwow.com</a><a className="button outline-light" href="tel:+16047611518">604-761-1518</a></div></section>
    <footer><div className="brand"><span>SNOW</span>REMOVAL.TV</div><p>Winter information and service connections for the Lower Mainland and Fraser Valley.</p><div><Link href="/">Home</Link><a href="https://plowwow.com">PlowWow.com</a></div><small>© 2026 SnowRemoval.tv</small></footer></main>
}

function GuideContent({name,detail}:{name:string;detail?:{focus:string;areas:string;conditions:string}}){return <><section className="article section"><p className="eyebrow red">Plan before the snowfall</p><h2>A practical winter plan for {name}.</h2><p>Reliable snow management starts before accumulation. Identify priority entrances, accessible routes, loading areas, fire access, drainage points and places where refreezing creates repeat hazards. Record the service trigger, response order and communication contacts before the forecast changes.</p>{detail&&<div className="local-box"><h3>Planning around {name}</h3><p>Local service commonly supports {detail.focus}. Planning should account for {detail.conditions}. Coverage extends throughout {detail.areas} and surrounding communities.</p></div>}<div className="three"><article><h3>Before the storm</h3><p>Confirm access, equipment staging, service triggers and sensitive surfaces. Mark curbs, drains and obstacles before they disappear under snow.</p></article><article><h3>During snowfall</h3><p>Keep priority routes open, monitor accumulation and coordinate plowing, hand clearing and de-icing as conditions change.</p></article><article><h3>After clearing</h3><p>Inspect for meltwater and refreeze, document the work and schedule return visits where temperature or precipitation requires them.</p></article></div></section><section className="article alt section"><p className="eyebrow red">Local responsibility</p><h2>Know the property—and verify the current bylaw.</h2><p>Municipal requirements and clearing timelines can change. Property owners and managers should verify current local rules directly with the municipality. Professional service does not replace the owner’s responsibility to maintain safe access and respond to changing conditions.</p></section></>}

function EquipmentContent(){const items=[['Shovel crews','Detailed clearing for entrances, stairs, walkways and hard-to-reach areas.'],['Snow blowers & sweepers','Efficient clearing on sidewalks, plazas and finished pedestrian surfaces.'],['Plow trucks & ATVs','Driveways, lanes, roadways and medium commercial parking areas.'],['Salters & de-icing equipment','Salt, brine and traction treatment before and after accumulation.'],['Skid steers & loaders','Pushing, stacking and relocating larger volumes of snow.'],['Backhoes & front loaders','Heavy handling for industrial yards, large lots and major accumulation.']];return <section className="article section"><p className="eyebrow red">Choose a capability</p><h2>Equipment sized to the site and accumulation.</h2><p>Send the address, property type, approximate square footage, priority areas, desired response timing and any access restrictions. Photos help the team recommend the correct equipment.</p><div className="request-grid">{items.map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p><a href={`mailto:wow@plowwow.com?subject=${encodeURIComponent(a+' request')}`}>Request this capability →</a></article>)}</div><div className="request-note"><strong>Useful request details</strong><span>Property address</span><span>Site type and size</span><span>Current depth and conditions</span><span>Timing or trigger</span><span>Photos and access notes</span></div></section>}

function CitiesContent(){return <section className="article section"><p className="eyebrow red">Metro Vancouver & Fraser Valley</p><h2>Choose a local snow-removal guide.</h2><p>Each guide covers local site conditions, planning priorities and direct access to PlowWow service support.</p><div className="city-grid city-directory">{Object.entries(cityNames).map(([slug,name])=><Link href={`/${slug}/`} key={slug}><strong>{name}</strong><span>Open guide →</span></Link>)}</div></section>}
